---

- name: Install nsd_extra_packages
  yum:
    name: "{{ nsd_extra_packages }}"
    state: present

- name: Install nsd_package
  yum:
    name: "{{ nsd_package }}"
    state: present

- name: Enable nsd_service
  service:
    name: "{{ nsd_service }}"
    enabled: yes

- name: "Create /etc/sysconfig/{{ nsd_service }}"
  template:
    src: RedHat.sysconfig.j2
    dest: "/etc/sysconfig/{{ nsd_service }}"
    mode: 0644
    # keep the original copy in case you need the defaults in it
    backup: yes
    validate: sh -n %s
  notify:
    - Restart nsd_service
